--to view data

show tables;

select count(*) from DASH_DB_SI.RETAIL.MARKETING_CAMPAIGN_METRICS;
select count(*) from DASH_DB_SI.RETAIL.PRODUCTS;
select count(*) from DASH_DB_SI.RETAIL.SALES;
select count(*) from DASH_DB_SI.RETAIL.SOCIAL_MEDIA;
select count(*) from DASH_DB_SI.RETAIL.SUPPORT_CASES;



SELECT 'MARKETING_CAMPAIGN_METRICS' AS table_name, COUNT(*) AS Total_records FROM DASH_DB_SI.RETAIL.MARKETING_CAMPAIGN_METRICS
UNION ALL
SELECT 'PRODUCTS' AS table_name, COUNT(*) AS Total_records FROM DASH_DB_SI.RETAIL.PRODUCTS
UNION ALL
SELECT 'SALES' AS table_name, COUNT(*) AS Total_records FROM DASH_DB_SI.RETAIL.SALES
UNION ALL
SELECT 'SOCIAL_MEDIA' AS table_name, COUNT(*) AS Total_records FROM DASH_DB_SI.RETAIL.SOCIAL_MEDIA
UNION ALL
SELECT 'SUPPORT_CASES' AS table_name, COUNT(*) AS Total_records FROM DASH_DB_SI.RETAIL.SUPPORT_CASES;
